### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by akbowen** [lazargugleta/instagramUnfollowers#9]
Hi,

I'm still getting this when I attempt to run the script:

```
Initializing WebDriver Manager
--------------------------------
--------------------------------
WebDriver Manager successfully initialized.
Traceback (most recent call last):
  File "/Users/akbowen/Downloads/instagramUnfollowers/followers.py", line 123, in <module>
    my_bot = InstaUnfollowers(username, password)
  File "/Users/akbowen/Downloads/instagramUnfollowers/followers.py", line 18, in __init__
    accept_all_btn = self.driver.find_element(By.CLASS_NAME, 'bIiDR')
  File "/Users/akbowen/Downloads/instagramUnfollowers/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 856, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/akbowen/Downloads/instagramUnfollowers/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/akbowen/Downloads/instagramUnfollowers/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".bIiDR"}
  (Session info: chrome=107.0.5304.87)
Stacktrace:
0   chromedriver                        0x0000000102c42a88 chromedriver + 4123272
1   chromedriver                        0x0000000102bce778 chromedriver + 3647352
2   chromedriver                        0x0000000102890ac4 chromedriver + 248516
3   chromedriver                        0x00000001028c6f68 chromedriver + 470888
4   chromedriver                        0x00000001028f9020 chromedriver + 675872
5   chromedriver                        0x00000001028bab10 chromedriver + 420624
6   chromedriver                        0x00000001028bbc30 chromedriver + 425008
7   chromedriver                        0x0000000102c14ae4 chromedriver + 3934948
8   chromedriver                        0x0000000102c17f24 chromedriver + 3948324
9   chromedriver                        0x0000000102c18508 chromedriver + 3949832
10  chromedriver                        0x0000000102c1eb30 chromedriver + 3975984
11  chromedriver                        0x0000000102c18b24 chromedriver + 3951396
12  chromedriver                        0x0000000102bf371c chromedriver + 3798812
13  chromedriver                        0x0000000102c352f0 chromedriver + 4068080
14  chromedriver                        0x0000000102c35444 chromedriver + 4068420
15  chromedriver                        0x0000000102c49450 chromedriver + 4150352
16  libsystem_pthread.dylib             0x000000018e6b606c _pthread_start + 148
17  libsystem_pthread.dylib             0x000000018e6b0e2c thread_start + 8
```

_Originally posted by @akbowen in https://github.com/lazargugleta/instagramUnfollowers/issues/7#issuecomment-1295948681_

**Comment by aravindhms** [comment]
Same error as stated by @akbowen

**Comment by lazargugleta** [comment]
Instagram updated their website structure hence the XPATHs have changed as well.
I updated and tested with new parameters and that should cover it.
